// announce
export const CREATE_ANNOUNCE = "CREATE_ANNOUNCE";
export const DELETE_ANNOUNCE = "DELETE_ANNOUNCE";
export const FETCH_ANNOUNCE = "FETCH_ANNOUNCE";
export const UPDATE_ANNOUNCE = "UPDATE_ANNOUNCE";
export const CHANGE_ANNOUNCE = "CHANGE_ANNOUNCE";

// channel
export const DELETE_CHANNEL = "DELETE_CHANNEL";
export const FETCH_CHANNEL = "FETCH_CHANNEL";
export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const FETCH_CHANNEL_COMMENT = "FETCH_CHANNEL_COMMENT";
export const DELETE_CHANNEL_COMMENT = "DELETE_CHANNEL_COMMENT";
export const CHANGE_CHANNEL_FILTER = "CHANGE_CHANNEL_FILTER";
export const TOGGLE_CHANNEL_STATE = "TOGGLE_CHANNEL_STATE";
export const CHANGE_SELECTED_CHANNEL = "CHANGE_FOCUS_CHANNEL";
export const TOGGLE_CHANNEL_MODAL_STATE = "TOGGLE_CHANNEL_MODAL_STATE";

// state
export const TOGGLE_SUMMIT = 'TOGGLE_SUMMIT';

// user
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const LOGIN_USER = 'LOGIN_USER';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const INITIAL_USER = 'INITIAL_USER';

export const CHANGE_USER_FORM = 'CHANGE_USER_FORM';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_USER = 'FETCH_USER';

